### PR TITLE
Adds emergency contact information

### LINKED ISSUE #47: As an intermidiate user, I can edit my employees' contact details
... so I can keep the latest updates.

### PR DESCRIPTION
**Pull request by Persdre**
so that users can add emergency contact of the employees

### CODE REVIEW

**Review by yanbingtao — DISMISSED** [review]
LGTM

**Review by Diwu-Yi — COMMENTED** [review]
LGTM

**Review by Diwu-Yi — DISMISSED** [review]
LGTM

**Comment by Persdre** [comment]
sad :(

**Pull request closed without merging**
