### PR TITLE
Branch v1.3 update dg zy

### PR DESCRIPTION
**Pull request by Diwu-Yi**
Add explanations, UML diagrams in progress.

### CODE REVIEW

**Comment by Diwu-Yi** [comment]
#97

**Review by yanbingtao — APPROVED** [review]
LGTM

**Review by yanbingtao — DISMISSED** [review]
LGTM

**Review by Persdre — DISMISSED** [review]
LGTM

**Review by yanbingtao — DISMISSED** [review]
LGTM

**Review by WM71811 — DISMISSED** [review]
LGTM

**Review by yanbingtao — APPROVED** [review]
LGTM

**Review by Persdre — APPROVED** [review]
LGTM

**Review by WM71811 — APPROVED** [review]
LGTM

**Pull request merged**
