### PR TITLE
Implement Ingredient List GUI and add tests

### LINKED ISSUE #147: Implement Ingredient List GUI
and ensure the features are working as expected.

### PR DESCRIPTION
**Pull request by Diwu-Yi**

### CODE REVIEW

**Comment by Diwu-Yi** [comment]
#147

**Review by WM71811 — DISMISSED** [review]
LGTM

**Review by yanbingtao — APPROVED** [review]
LGTM

**Review by WM71811 — APPROVED** [review]
LGTM

**Pull request merged**
